# Generated by Django 4.2 on 2023-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_column="ID", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=45)),
                ("name", models.CharField(max_length=45)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
            options={"db_table": "member", "managed": False,},
        ),
    ]
