# Generated by Django 4.2 on 2023-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
